const data = {
  east: {
    Bedok: [
      "Bayshore",
      "Bedok North",
      "Bedok Reservoir",
      "Bedok South",
      "Frankel",
      "Kaki Bukit",
      "Kembangan",
      "Siglap",
    ],
    Changi: ["Changi Airport", "Changi Point", "Changi West"],
    "Changi Bay": [],
    "Pasir Ris": [
      "Flora Drive",
      "Loyang East",
      "Loyang West",
      "Pasir Ris Central",
      "Pasir Ris Drive",
      "Pasir Ris Park",
      "Pasir Ris Wafer Fab Park",
      "Pasir Ris West",
    ],
    "Paya Lebar": [
      "Airport Road",
      "Paya Lebar East",
      "Paya Lebar North",
      "Paya Lebar West",
      "PLAB",
    ],
    Tampines: [
      "Simei",
      "Tampines East",
      "Tampines North",
      "Tampines West",
      "Xilin",
    ],
  },
  west: {
    "Boon Lay": ["Liu Fang", "Samulun", "Shipyard", "Tukang"],
    "Bukit Batok": [
      "Brickworks",
      "Bukit Batok Central",
      "Bukit Batok East",
      "Bukit Batok West",
      "Gombak",
      "Guilin",
      "Hillview",
      "Hong Kah North",
    ],
    "Bukit Panjang": [
      "Bangkit",
      "Dairy Farm",
      "Fajar",
      "Jelebu",
      "Nature Reserve",
      "Saujana",
      "Senja",
    ],
    "Choa Chu Kang": [
      "Choa Chu Kang Central",
      "Choa Chu Kang North",
      "Keat Hong",
      "Peng Siang",
      "Teck Whye",
      "Yew Tee",
    ],
    Clementi: [
      "Clementi Central",
      "Clementi North",
      "Clementi West",
      "Clementi Woods",
      "Faber",
      "Pandan",
      "Sunset Way",
      "Toh Tuck",
      "West Coast",
    ],
    "Jurong East": [
      "International Business Park",
      "Jurong Gateway",
      "Jurong Port",
      "Jurong River",
      "Lakeside",
      "Penjuru Crescent",
      "Teban Gardens",
      "Toh Guan",
      "Yuhua East",
      "Yuhua West",
    ],
    "Jurong West": [
      "Boon Lay Place",
      "Chin Bee",
      "Hong Kah",
      "Jurong West Central",
      "Kian Teck",
      "Safti",
      "Taman Jurong",
      "Wenya",
      "Yunnan",
    ],
    Pioneer: [
      "Benoi Sector",
      "Gul Basin",
      "Gul Circle",
      "Joo Koon",
      "Pioneer Sector",
    ],
    Tengah: [],
    Tuas: [
      "Tengeh",
      "Tuas Bay",
      "Tuas North",
      "Tuas Promenade",
      "Tuas View",
      "Tuas View Extension",
    ],
    "Western Islands": ["Jurong Island and Bukom", "Semakau", "Sudong"],
    "Western Water Catchment": [],
  },
  north: {
    "Central Water Catchment": [],
    "Lim Chu Kang": [],
    Mandai: ["Mandai East", "Mandai Estate", "Mandai West"],
    Sembawang: [
      "Admiralty",
      "Sembawang Central",
      "Sembawang East",
      "Sembawang North",
      "Sembawang Spring",
      "Sembawang Straits",
      "Senoko North",
      "Senoko South",
      "The Wharves",
    ],
    Simpang: [
      "Pulau Seletar",
      "Simpang North",
      "Simpang South",
      "Tanjong Irau",
    ],
    "Sungei Kadut": [
      "Gali Batu",
      "Kranji",
      "Pang Sua",
      "Reservoir View",
      "Turf Club",
    ],
    Woodlands: [
      "Greenwood Park",
      "Midview",
      "North Coast",
      "Senoko West",
      "Woodgrove",
      "Woodlands East",
      "Woodlands Regional Centre",
      "Woodlands South",
      "Woodlands West",
    ],
    Yishun: [
      "Khatib",
      "Lower Seletar",
      "Nee Soon",
      "Northland",
      "Springleaf",
      "Yishun Central",
      "Yishun East",
      "Yishun South",
      "Yishun West",
    ],
  },
  central: {
    Bishan: ["Bishan East", "Marymount", "Upper Thomson"],
    "Bukit Merah": [
      "Alexandra Hill",
      "Alexandra North",
      "Bukit Ho Swee",
      "Bukit Merah",
      "City Terminals",
      "Formerly called Tanjong Pagar Subzone",
      "Depot Road",
      "Everton Park",
      "Henderson Hill",
      "Kampong Tiong Bahru",
      "Maritime Square",
      "Formerly called HarbourFront Subzone",
      "Redhill",
      "Singapore General Hospital",
      "Telok Blangah Drive",
      "Telok Blangah Rise",
      "Telok Blangah Way",
    ],
    "Bukit Timah": [
      "Tiong Bahru",
      "Tiong Bahru Station",
      "Anak Bukit",
      "Coronation Road",
      "Farrer Court",
      "Hillcrest",
      "Holland Road",
      "Leedon Park",
    ],
    "Downtown Core": [
      "Swiss Club",
      "Ulu Pandan",
      "Anson",
      "Bayfront Subzone",
      "Bugis",
      "Cecil",
      "Central Subzone",
      "City Hall",
      "Clifford Pier",
      "Marina Centre",
      "Maxwell",
      "Nicoll",
      "Phillip",
    ],
    Geylang: [
      "Raffles Place",
      "Tanjong Pagar",
      "Aljunied",
      "Geylang East",
      "Kallang Way",
    ],
    Kallang: [
      "Kampong Ubi",
      "MacPherson",
      "Bendemeer",
      "Boon Keng",
      "Crawford",
      "Geylang Bahru",
      "Kallang Bahru",
      "Kampong Bugis",
      "Kampong Java",
    ],
    "Marine Parade": [
      "Lavender",
      "Tanjong Rhu",
      "Marina East",
      "Marina East",
      "Marina South",
    ],
    Museum: ["Marina South", "East Coast", "Katong"],
    Newton: [
      "Marina East",
      "Marine Parade",
      "Mountbatten",
      "Bras Basah",
      "Dhoby Ghaut",
      "Fort Canning",
    ],
    Novena: [
      "Cairnhill",
      "Goodwood Park",
      "Istana Negara",
      "Monk's Hill",
      "Newton Circus",
    ],
    Orchard: ["Orange Grove", "Balestier", "Dunearn"],
    Outram: ["Malcolm", "Moulmein", "Mount Pleasant", "Boulevard"],
    Queenstown: [
      "Somerset",
      "Tanglin",
      "China Square",
      "Chinatown",
      "Pearl's Hill",
      "People's Park",
      "Commonwealth",
      "Dover",
      "Ghim Moh",
      "Holland Drive",
      "Kent Ridge",
      "Margaret Drive",
      "Mei Chin",
      "National University of Singapore",
      "one-north",
    ],
    "River Valley": [
      "Pasir Panjang 1",
      "Pasir Panjang 2",
      "Port",
      "Queensway",
      "Singapore Polytechnic",
    ],
    Rochor: [
      "Tanglin Halt",
      "Institution Hill",
      "Leonie Hill",
      "One Tree Hill",
      "Oxley",
      "Paterson",
      "Bencoolen",
      "Farrer Park",
      "Kampong Glam",
      "Little India",
    ],
    "Singapore River": ["Mackenzie", "Mount Emily", "Rochor Canal"],
    "Southern Islands": ["Selegie", "Sungei Road"],
    Tanglin: ["Victoria", "Boat Quay", "Clarke Quay", "Robertson Quay"],
    "Toa Payoh": [
      "Sentosa",
      "Southern Group",
      "Straits View",
      "Straits View",
      "Chatsworth",
      "Nassim",
      "Ridout",
      "Tyersall",
      "Bidadari",
      "Boon Teck",
      "Braddell",
      "Joo Seng",
    ],
  },
  northEast: {
    "Ang Mo Kio": [
      "Ang Mo Kio Town Centre",
      "Cheng San",
      "Chong Boon",
      "Kebun Baru",
      "Sembawang Hills",
      "Shangri-La",
      "Tagore",
      "Townsville",
      "Yio Chu Kang",
      "Yio Chu Kang East",
      "Yio Chu Kang North",
      "Yio Chu Kang West",
    ],
    Hougang: [
      "Defu Industrial Park",
      "Hougang Central",
      "Hougang East",
      "Hougang West",
      "Kangkar",
      "Kovan",
      "Lorong Ah Soo",
      "Lorong Halus",
      "Tai Seng",
      "Trafalgar",
    ],
    "North-Eastern Islands": [],
    Punggol: [
      "Coney Island",
      "Matilda",
      "Northshore",
      "Punggol Canal",
      "Punggol Field",
      "Punggol Town Centre",
      "Waterway East",
    ],
    Seletar: [
      "Pulau Punggol Barat",
      "Pulau Punggol Timor",
      "Seletar",
      "Seletar Aerospace Park",
    ],
    Sengkang: [
      "Anchorvale",
      "Compassvale",
      "Fernvale",
      "Lorong Halus North",
      "Rivervale",
      "Sengkang Town Centre",
      "Sengkang West",
    ],
    Serangoon: [
      "Lorong Chuan",
      "Seletar Hills",
      "Serangoon Central",
      "Serangoon Garden",
      "Serangoon North",
      "Serangoon North Industrial Estate",
      "Upper Paya Lebar",
    ],
  },
};
